version: '3'
services:
  db:
    image: db2:latest
    #build: ./db2
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: thisisthepwd
    command: db2start
  app:
    image: java-web-test:latest
    # build: ./app
    environment:
      DB2_PORT: 50000
      DB2_HOST: db
    ports:
      - "9080:9080"
      - "9443:9443"
    depends_on:
      - db
